[overrides]
"componentized:config" = { path = "./wit/overrides/componentized-config" }
"componentized:valkey" = { path = "./wit/overrides/componentized-valkey" }
"wasi:config" = { path = "./wit/overrides/wasi-config" }
"wasi:keyvalue" = { path = "./wit/overrides/wasi-keyvalue" }
