[package]
name = "filesystem-lifecycle"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { workspace = true }
wit-bindgen = { workspace = true }
