
interface types {
    type service-id = string;
    type service-instance-id = service-id;
    type service-binding-id = service-id;

    record credential {
        key: string,
        value: string,
    }
    record request {
        key: string,
        value: string,
    }
    type scope = string;
    type tier = string;

    type error = string;
}
